name: CI

on:
  push:
    branches: main
  pull_request:

jobs:
  clang-format-checking:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: RafikFarhad/clang-format-github-action@v6
        with:
          sources: "**/*.ino,**/*.h,**/*.c,**/*.cpp,**/*.hpp"

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Install Meson and Ninja
        run: uv tool install meson

      - name: Setup build
        run: meson setup build

      - name: Run tests
        run: meson test -C build

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v2

      - name: Cache Arduino dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.arduino15
            ~/Arduino/libraries
          key: arduino-${{ hashFiles('sketch.yaml') }}

      - name: Compile sketch
        run: arduino-cli compile --profile esp32s3
